### PR TITLE
Some Lib Update

### PR DESCRIPTION
**Pull request by ffchung**
Not full test. But it working well on my portal.
It look a bit faster.

### CODE REVIEW

**Comment by gregstoll** [comment]
Thanks! I'll try to look at this soon.

**Comment by gregstoll** [comment]
Thanks, this is great! It does seem a bit faster on my machine too, and I'm excited about getting whatever security fixes have happened in the meantime.

For the record, I verified that the stock downloads of these packages match what's in the PR, with the exception of the curly brace->square brace fixes in JSON.php.

Thanks so much!

**Comment by ffchung** [comment]
Thanks for your work too. Your project already save more time. I just try make some help on this project.

**Comment by kaeni1Ohkohd** [comment]
@ffchung: You beat me to getting the adodb upgrade done, probably by several months  ;-). Very much appreciated

**Comment by miceno** [comment]
Hi all! 

Sorry to open this issue after a while, but the changes breaks compatibility with PHP 8.1, since Smarty and adodb are using strftime, and PHP 8.1 deprecates strftime. I am getting weird deprecated warnings on my dev environment as of now :(

Is there any other alternative that is compatible with PHP 8.1?

By the way, what version of PHP are you using?

EDIT: I have realized that if I reload the page, deprecated warnings dissapear ... I will research it a bit more.

**Comment by miceno** [comment]
I realized that I changed the Dockerfile to use PHP 8.1 and then deprecated messages show up. I confirm that running on PHP 8.0 does not show deprecated messages.

**Comment by gregstoll** [comment]
Ugh, that's annoying. We got rid of `strftime` in Gallery code proper in #70, but I hadn't thought about dependencies.

I'm running PHP 8.1, but it looks like I turned off the deprecated messages because they were so spammy at one point :-)

**Pull request merged**
